version: "3"

services:
  mariadb:
    env_file:
     - .env
    container_name: "mariadb"
    restart: always
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - database:/var/lib/mysql
      #- /home/cruiz-de/data/db/:/var/lib/mysql
      #- type: bind
      #  source: /home/cruiz-de/data/db
      #  target: /var/lib/mysql
    networks:
      - nolan

  wordpress:
    env_file:
      - .env
    container_name: "wordpress"
    restart: always
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - wordpressvol:/var/www/html/wordpress
      #- type: bind
      #  source: /home/cruiz-de/data/wp
      #  target: /var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - nolan
  
  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - wordpressvol:/var/www/html/wordpress/
      #- type: bind
      #  source: /home/cruiz-de/data/wp
      #  target: /var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - nolan

volumes:
  database:
    driver_opts:
      o: bind
      type: none
      device: /home/cruiz-de/data/database
  wordpressvol: 
    driver_opts:
      o: bind
      type: none
      device: /home/cruiz-de/data/wordpress

networks:
  nolan: