version: "3"

services:

  mariadb:
    container_name: "mariadb"
    restart: always

    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mdbvol:/var/lib/mysql

  wordpress:
    container_name: "wordpress"
    restart: always
    build:
       context: ./requirements/wordpress/
       dockerfile: Dockerfile
    depends_on:
      - mariadb
  
  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile