version: "3"

services:
  mariadb:
    env_file:
     - .env
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - nolan

  wordpress:
    env_file:
      - .env
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - wp_volume:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - nolan
  
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www/html/wordpress/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - nolan

volumes:
  db_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/cruiz-de/data/database
  wp_volume: 
    driver_opts:
      o: bind
      type: none
      device: /home/cruiz-de/data/wordpress

networks:
  nolan:
    name: nolan