CREATE USER IF NOT EXISTS root@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
SET PASSWORD FOR root@'%' = PASSWORD('$MYSQL_ROOT_PASSWORD');
GRANT ALL ON *.* TO root@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
SET PASSWORD FOR '$MYSQL_USER'@'%' = PASSWORD('$MYSQL_PASSWORD');
CREATE DATABASE IF NOT EXISTS '$MYSQL_DATABASE';
GRANT ALL ON '$MYSQL_DATABASE'.* TO '$MYSQL_USER'@'%';